import ASidebar from "@/components/Dashboard/Asidebar";
import Navbar from "@/components/Dashboard/Navbar";

export const metadata: any = {
  title: "Dashboard",
  description: "Generated by create next app",
};

const DashboardLayout = ({ children }: any) => {
  return (
    <div className="w-full h-screen flex">
      <div className="w-1/6 h-full">
        <ASidebar />
      </div>
      <div className="w-5/6 h-full flex flex-col">
        <Navbar />
        <div className="flex-grow bg-[#fafafa] p-4">{children}</div>
      </div>
    </div>
  );
};

export default DashboardLayout;
